import { Inter, IBM_Plex_Mono, Encode_Sans_Expanded } from "next/font/google";
// import "./globals.css";
import "./style.scss";
import About from "./components/About/About";
import Header from "./components/Header/Header";
import Projects from "./components/Projects/Projects";
import InteractiveBG from "./components/Interactive/InteractiveBG";
import TechStack from "./components/TechStack/TechStack";

const inter = Inter({ subsets: ["latin"] });
const ibmPlexMono = IBM_Plex_Mono({ subsets: ["latin"], weight: ["400"] });
const encodeSansExpanded = Encode_Sans_Expanded({subsets: ["latin"], weight: ["400"]})

export const metadata = {
  title: "Darina's Portfolio",
  description: "Generated by create next app (?)",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${ibmPlexMono.className}`}>
        {children}
        <InteractiveBG />
        <Header font={encodeSansExpanded.className}/>
        <About font={encodeSansExpanded.className}/>
        <TechStack />
        <Projects />
      </body>
    </html>
  );
}
